name: BladePipe Install & Tail Logs

on:
  workflow_dispatch: {}

jobs:
  install-and-tail:
    runs-on: ubuntu-latest
    timeout-minutes: 360

    steps:
      - name: Show runner info
        run: |
          uname -a
          id

      - name: Set up Java (Temurin 8)
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '8'

      - name: Ensure bladepipe user exists (optional but safer)
        run: |
          set -eux
          if ! id bladepipe &>/dev/null; then
            sudo useradd -m -d /home/bladepipe bladepipe
          fi
          if ! sudo grep -q '^bladepipe ' /etc/sudoers; then
            echo 'bladepipe ALL=(ALL) NOPASSWD:ALL' | sudo tee -a /etc/sudoers
          fi
          ls -ld /home/bladepipe

      - name: Run official installer (non-interactive)
        shell: bash
        run: |
          set -euo pipefail
          # 直接执行你的一行脚本，并将 4 行配置通过 stdin 传入
          sudo /bin/bash -c "$(curl -fsSL https://download.bladepipe.com/binary/install_run.sh)" <<'EOF'
          bladepipe.auth.ak=aky1cj8w4s5qtqcxy5fu627v026r9un82b738y9nd79so793750dv1a3t1430g1
          bladepipe.auth.sk=skp93j846395g9mru5631pqvm1261ln80uxza93d0r445e08k73fq3q4x593102
          bladepipe.worker.wsn=wsn792570f4s1pl9tsm962hhv7azernf238jky0iezgefggmk637no2qkvnyp2d7
          bladepipe.console.domain=west-us-1.bladepipe.com
          EOF

      - name: Wait for log file to appear
        shell: bash
        run: |
          set -euo pipefail
          LOG=~/logs/bladepipe/worker/sidecar.log
          ALT=/home/bladepipe/logs/bladepipe/worker/sidecar.log

          echo "[INFO] Waiting for log file to be created ..."
          for i in $(seq 1 60); do
            if [ -f "$LOG" ]; then
              echo "[INFO] Found $LOG"; export BP_LOG="$LOG"; break
            elif [ -f "$ALT" ]; then
              echo "[INFO] Found $ALT"; export BP_LOG="$ALT"; break
            else
              sleep 5
            fi
          done

          if [ -z "${BP_LOG:-}" ]; then
            echo "[WARN] Log file not found yet. Current tree:"
            sudo ls -la ~/logs || true
            sudo ls -la /home/bladepipe/logs || true
            BP_LOG="$ALT"
          fi
          echo "BP_LOG=$BP_LOG" >> $GITHUB_ENV

      - name: Tail BladePipe worker logs (keep job alive)
        shell: bash
        run: |
          set -euo pipefail
          echo "[INFO] Tailing logs from: $BP_LOG"
          sudo tail -n 200 -F "$BP_LOG"
